name: connection_package
description: Tracks changes in network connectivity
version: 0.0.6+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0
  # Beyond Bloc

  connectivity: ">=0.4.8+6 <2.0.0"
  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test: ">=1.14.0 <2.0.0 "

flutter:
