name: connection_package
description: A new Flutter package project.
version: 0.0.5+0
homepage: https://github.com/GitHubStuff/connection_package.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  # Beyond Bloc
  app_exception:
    git:
      url: https://github.com/GitHubStuff/app_exception.git
  connectivity: ">=0.4.8+6 <2.0.0"
  data_connection_checker: ^0.3.4
  tracers:
    git:
      url: https://github.com/GitHubStuff/tracers.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test: ">=1.14.0 <2.0.0 "

flutter:
