name: example_product
description: Listens for changes in network connection
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  connection_package:
    path: "../"
  hud_scaffold:
    git:
      url: https://github.com/GitHubStuff/hud_scaffold.git
  mode_theme:
    git:
      url: https://github.com/GitHubStuff/mode_theme.git
  tracers:
    git:
      url: https://github.com/GitHubStuff/tracers.git
  after_layout: ^1.0.7+2
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3
  equatable: ^1.2.0
  flutter_bloc: ^6.0.1
  flutter_modular: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
